### ISSUE TITLE
Why no cron job is spawned in Leap 15.3?

### ISSUE THREAD

**Issue by powerjungle** [yast/yast-online-update-configuration#32]
When running:

`sudo yast2 online_update_configuration`

and configuring the automatic update from the terminal, no job appears in /etc/cron.*ly, there are actually no directories for cron there to start with.

In tumbleweed using the GUI, the cron job appears. So what gives?

Also, when trying to disable the function in tumbleweed, it doesn't remove the file from /etc/cron.daily and when running the gui again it shows up as enabled. This tool is pretty useless...Needs to be run as root to disable it, ran it from the terminal manually, don't know why it didn't prompt for a password again when running the gui.

So yeah whatever, I give up.

**Comment by dgdavid** [comment]
Hi!

> When running:
> 
> `sudo yast2 online_update_configuration`
> 
> and configuring the automatic update from the terminal, no job appears in /etc/cron.*ly, there are actually no directories for cron there to start with.

I have not tested it in  Leap 15.3 yet, **BUT**:


---

> 
> In tumbleweed using the GUI, the cron job appears. So what gives?

I didn't understand the question. But after

```
1. run `yast2 online_update_configuration`
2. check `Automatic Online Update` checkbox
3. select `daily` Interval
4. click `OK` button
```

I can see 

➜ localhost:~ # ls -al /etc/cron.daily/
total 4
drwxr-xr-x 1 root root   52 Dec 10 12:19 .
drwxr-xr-x 1 root root 4400 Dec  9 16:31 ..
lrwxrwxrwx 1 root root   32 Dec 10 12:19 opensuse.org-online_update -> [/usr/lib/YaST2/bin/online_update](https://github.com/yast/yast-online-update-configuration/blob/master/src/bin/online_update)

which reads the configuration from [/etc/sysconfig/automatic_online_update](https://github.com/yast/yast-online-update-configuration/blob/46341a765a430d4922417db3a0dab56a056ad88b/src/bin/online_update#L8-L21).

And I have checked that `yast2 online_update_configuration` properly updates that file according to user choices.

> 
> Also, when trying to disable the function in tumbleweed, it doesn't remove the file from /etc/cron.daily and when running the gui again it shows up as enabled. 

Is **NOT** the case for me. The symlink is removed and the UI behaves as expected.

> This tool is pretty useless...Needs to be run as root to disable it, ran it from the terminal manually, don't know why it didn't prompt for a password again when running the gui.
> 

Actually, it is accessible from _YaST Software -> Configuration -> Online Update... (Ctrl + O)_ menu entry. And yes, so many YaST modules ask for a root password since it is an administrator tool.


> So yeah whatever, I give up.

Even before we can give feedback to you :disappointed:
